site_name: Exploring Secure Boot
site_url: https://exploring-secure-boot.readthedocs.io

nav: 
  - Home: index.md
  - Background: background.md
  - Experimental Overview: expt-overview.md
  - Resource Notes: paper_notes.md
  - Microcontroller Notes: microcontrollers.md

theme: readthedocs
repo_url: https://github.com/Galactius/exploring-secure-boot
edit_uri: blob/main/research-docs
